# Generated by Django 2.0.3 on 2018-04-16 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('changed_times', models.IntegerField(default=0)),
                ('text', models.TextField(help_text='row text')),
                ('tokens_and_pos', models.TextField(blank=True, help_text='json object that segment tokens list')),
                ('tagged', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('tag_type', models.CharField(default=0, help_text='tag type', max_length=255)),
                ('file_name', models.CharField(default=0, help_text='file_name', max_length=255)),
                ('last_changed_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_start_id', models.IntegerField(default=0)),
                ('sentence_end_id', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
