# Generated by Django 2.0.3 on 2018-04-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='last_changed_by_id',
            new_name='last_changed_by',
        ),
    ]
